# Generated by Django 5.2.6 on 2025-09-28 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_brand_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_type",
                    models.CharField(
                        choices=[
                            ("battery", "Battery Issue 🔋"),
                            ("motor", "Motor Issue ⚡"),
                            ("temp", "Temperature 🌡️"),
                            ("brake", "Brake Issue 🛑"),
                            ("general", "General Fault ⚠️"),
                        ],
                        max_length=50,
                    ),
                ),
                ("major_problem", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
