# Generated by Django 5.2.6 on 2025-09-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_problemreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="MajorProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warning_type",
                    models.CharField(
                        choices=[
                            ("battery", "Battery Issue 🔋"),
                            ("motor", "Motor Issue ⚡"),
                            ("temp", "Temperature 🌡️"),
                            ("brake", "Brake Issue 🛑"),
                            ("general", "General Fault ⚠️"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="problemreport",
            name="major_problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.majorproblem",
            ),
        ),
    ]
